### ISSUE TITLE
stat.inkからスプラ2のマップとルールを取得して、discordに流す

### ISSUE THREAD

**Issue by nikuzuki** [unasuke/bot-bahamut#19]
## 概要
stat.ink内にあるAPIを使ってマップとルールを取得し
discord上でコマンドを叩くとマップとルールを表示する

## 変更理由
スマホアプリからマップとルール確認が面倒

**Comment by nikuzuki** [comment]
ガチマッチは実装した。
ナワバリバトルとサーモンラン、リーグマッチが求められている

**Comment by nikuzuki** [comment]
一通り実装したのでclose

**Comment by unasuke** [comment]
good job!
